# Generated by Django 4.2.26 on 2026-07-12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_staticmix_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmix',
            name='separator',
            field=models.CharField(
                choices=api.models.SEP_CHOICES,
                default='spleeter',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='staticmix',
            name='separator',
            field=models.CharField(
                choices=api.models.SEP_CHOICES,
                default='spleeter',
                max_length=40,
            ),
        ),
    ]
