# Generated by Django 5.2.16 on 2026-07-13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_mel_roformer_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmix',
            name='separator',
            field=models.CharField(choices=api.models.SEP_CHOICES,
                                   default='spleeter', max_length=40),
        ),
        migrations.AlterField(
            model_name='staticmix',
            name='separator',
            field=models.CharField(choices=api.models.SEP_CHOICES,
                                   default='spleeter', max_length=40),
        ),
    ]
